<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ma session</title>
</head>
<body>
    <form action="" method="post">
        <fieldset>
            <legend>Ma Session</legend>
            <div>
                <label for="MonId">Identifiant</label>
                <input type="text" name="MonId" id="MonId" placeholder="Identifiant">
            </div>
            <div>
                <label for="password">Mot de pass</label>
                <input type="password" name="password" id="password" placeholder="Mot de pass">
            </div>
            <button type="submit" name="connexion">connexion</button>
        </fieldset>
    </form>
</body>
</html>