<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
</head>
<body>
<form action="" method="post">
        <fieldset>
            <legend>Inscription</legend>
            <label for="login">Identifiant:</label></p>
            <input type="text" id="login" name="login" />
            <p>
            <label for="pwd">Mot de passe:</label></p>
            <input type="password" id="pwd" name="pwd" />
            <p>
            <label for="pwd1">Confirmer Mot de passe:</label></p>
            <input type="password" id="pwd1" name="pwd1" />
            <br>
            <button type="submit" name="bouton">Envoyer</button>
        </fieldset>
    </form>
</body>
</html>