<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connexion</title>
</head>
<body>
    <form action="" method="post">
        <fieldset>
            <legend>
                CONNEXION
            </legend>
            <label for="id_user">Identifiant</label>
            <input type="text" name="id_user" id="id_user"><br/> 
            <label for="pwd">Mot de pass</label>
            <input type="password" name="pwd" id="pwd"><br/> 
            <button type="submit" name="connexion">Connexion</button>
        </fieldset>

    </form>
</body>
</html>