<div>
        <form action="" method="post">
            <fieldset>
                <legend>INSCRIPTION</legend>
                <label for="fname"> Nom : </label>
            <input type="text" name="fname" id="fname" ><br>
            <label for="lname"> Prenom : </label>
            <input type="text" name="lname" id="lname"><br>
            <label for="id_user"> Identifiant : </label>
            <input type="text" name="id_user" id="id_user"><br>
            <label for="pwd"> Mot de pass : </label>
            <input type="password" name="pwd" id="pwd"><br>
            <label for="pwd"> Confirmer le mot de pass : </label>
            <input type="password" name="cpwd" id="cpwd"><br>
            <input type="submit" name="inscription" id="inscription" value="s'inscrire"><br>
            </fieldset>
            
        </form>
        <!-- <form action="index.php?page=recherche" method="post">
            <input type="search" name="motcle"/>
            <button type="submit" >ok</button>
        </form> -->
    </div>