<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reservation</title>
</head>
<body>
    <form action="" method="post">
        <fieldset>
            <legend>
                RESERVATION
            </legend>
            <input type="date" name="reserv_date" id="reserv_date"><br/> 
            <input type="time" name="reserv_heure" id="reserv_heure"><br/> 
            <button type="submit" name="reservation">Reserver</button>
        </fieldset>

    </form>
</body>
</html>