<form action="" method="post">
        <fieldset>
            <legend>
               CHOISSEZ VOS PLATS
            </legend>
        
            <label for="plat_africain">Plats :</label>
            <select id="plat_africain" name="plat_africain">
                <option value="pate">Pâte de maïs</option>
                <option value="piron">Eba</option>
                <option value="atassi">Atassi</option>
                <option value="atcheke">Atchèkè</option>
            </select>
            <input type="submit">

            <button type="submit" name="connexion">Connexion</button>
            <p>Vous n'avez pas encore de compte. Veuillez vous <a href="index.php?goto=user&target=CreateUser">Inscrire</a></p>
        </fieldset>

    </form>