<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connection à la Base de </title>
</head>
<body>
    
</body>
    <form action="controllers\traitement.php" method="post">
        <p><label for="fname">Nom: </label>
        <input type="text" name="fname" id="fname"></p>
    
        <p><label for="lname">Prénom: </label>
        <input type="text" name="lname" id="lname"></p>

        <p><label for="id_user">identifiant: </label>
        <input type="text" name="id_user" id="id_user"></p>

        <p><label for="pwd">Mot de pass: </label>
        <input type="password" name="pwd" id="pwd"></p>

        <button type="submit" name="inscription" value="s'inscrire">Inscription</button>
    </form>
</html>